name: packer

on:
  push:
permissions:
  id-token: write # This is required for requesting the JWT

env:

  PRODUCT_VERSION: "1.10.0" # or:   "latest"
  
  
jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::874599947932:role/gitaws
          role-session-name: github-actions
          aws-region: us-east-1  

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.10.0"

      - name: Run `packer init`
        id: init
        run: "packer init ./jenkinsubuntu.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./jenkinsubuntu.pkr.hcl"

      - name: Run 'packer build'
        id: build
        run: packer build  ./jenkinsubuntu.pkr.hcl        
