name: Run Packer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
        unzip packer_1.7.4_linux_amd64.zip
        sudo mv packer /usr/local/bin/
        
    - name: packer init
      run: packer init . 
      
    - name: Validate Packer configuration
      run: packer validate jenkinsubuntu.pkr.hcl

    - name: Build using Packer
      run: packer build jenkinsubuntu.pkr.hcl
