name: Build Jenkins AMI
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository containing Packer files (e.g., prakashecho/jenkinspacker)'
        required: true
        default: 'prakashecho/packer'
      branch:
        description: 'Branch to use'
        required: true
        default: 'main'

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout Packer files
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.branch }}
          path: packer-files

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::874599947932:role/gitaws
          role-session-name: github-actions
          aws-region: us-east-1  

      - name: Install AWS CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq

      - name: Setup `packer`
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: "1.8.6" # or a different version
          plugins: |
            github.com/hashicorp/amazon@1.3.2 # or the compatible version

      - name: Run `packer init`
        id: init
        run: |
          cd packer-files
          packer init ./jenkinsubuntu.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: |
          cd packer-files
          packer validate ./jenkinsubuntu.pkr.hcl

      - name: Run 'packer build'
        id: build
        run: |
          cd packer-files
          packer build ./jenkinsubuntu.pkr.hcl
